from PyQt5.QtWidgets import QMessageBox

from algos import *
import time
from PyQt5 import QtWidgets
from PyQt5 import QtCore
from PyQt5 import QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(666, 799)

        self.round = 1

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setStyleSheet("background-color: #3A3B3C")
        self.background.setGeometry(QtCore.QRect(0, 0, 931, 771))
        self.background.setMouseTracking(False)
        self.background.setAutoFillBackground(True)
        self.background.setText("")
        self.background.setObjectName("background")
        self.i11 = QtWidgets.QLineEdit(self.centralwidget)
        self.i11.setGeometry(QtCore.QRect(60, 20, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i11.setFont(font)
        self.i11.setMaxLength(1)
        self.i11.setFrame(False)
        self.i11.setCursorPosition(0)
        self.i11.setAlignment(QtCore.Qt.AlignCenter)
        self.i11.setClearButtonEnabled(False)
        self.i11.setObjectName("i11")
        self.i15 = QtWidgets.QLineEdit(self.centralwidget)
        self.i15.setGeometry(QtCore.QRect(500, 20, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i15.setFont(font)
        self.i15.setMaxLength(1)
        self.i15.setFrame(False)
        self.i15.setCursorPosition(0)
        self.i15.setAlignment(QtCore.Qt.AlignCenter)
        self.i15.setClearButtonEnabled(False)
        self.i15.setObjectName("i15")
        self.i14 = QtWidgets.QLineEdit(self.centralwidget)
        self.i14.setGeometry(QtCore.QRect(390, 20, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i14.setFont(font)
        self.i14.setMaxLength(1)
        self.i14.setFrame(False)
        self.i14.setCursorPosition(0)
        self.i14.setAlignment(QtCore.Qt.AlignCenter)
        self.i14.setClearButtonEnabled(False)
        self.i14.setObjectName("i14")
        self.i13 = QtWidgets.QLineEdit(self.centralwidget)
        self.i13.setGeometry(QtCore.QRect(280, 20, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i13.setFont(font)
        self.i13.setMaxLength(1)
        self.i13.setFrame(False)
        self.i13.setCursorPosition(0)
        self.i13.setAlignment(QtCore.Qt.AlignCenter)
        self.i13.setClearButtonEnabled(False)
        self.i13.setObjectName("i13")
        self.i12 = QtWidgets.QLineEdit(self.centralwidget)
        self.i12.setGeometry(QtCore.QRect(170, 20, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i12.setFont(font)
        self.i12.setMaxLength(1)
        self.i12.setFrame(False)
        self.i12.setCursorPosition(0)
        self.i12.setAlignment(QtCore.Qt.AlignCenter)
        self.i12.setClearButtonEnabled(False)
        self.i12.setObjectName("i12")
        self.i23 = QtWidgets.QLineEdit(self.centralwidget)
        self.i23.setGeometry(QtCore.QRect(280, 130, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i23.setFont(font)
        self.i23.setMaxLength(1)
        self.i23.setFrame(False)
        self.i23.setCursorPosition(0)
        self.i23.setAlignment(QtCore.Qt.AlignCenter)
        self.i23.setClearButtonEnabled(False)
        self.i23.setObjectName("i23")
        self.i25 = QtWidgets.QLineEdit(self.centralwidget)
        self.i25.setGeometry(QtCore.QRect(500, 130, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i25.setFont(font)
        self.i25.setMaxLength(1)
        self.i25.setFrame(False)
        self.i25.setCursorPosition(0)
        self.i25.setAlignment(QtCore.Qt.AlignCenter)
        self.i25.setClearButtonEnabled(False)
        self.i25.setObjectName("i25")
        self.i24 = QtWidgets.QLineEdit(self.centralwidget)
        self.i24.setGeometry(QtCore.QRect(390, 130, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i24.setFont(font)
        self.i24.setMaxLength(1)
        self.i24.setFrame(False)
        self.i24.setCursorPosition(0)
        self.i24.setAlignment(QtCore.Qt.AlignCenter)
        self.i24.setClearButtonEnabled(False)
        self.i24.setObjectName("i24")
        self.i21 = QtWidgets.QLineEdit(self.centralwidget)
        self.i21.setGeometry(QtCore.QRect(60, 130, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i21.setFont(font)
        self.i21.setMaxLength(1)
        self.i21.setFrame(False)
        self.i21.setCursorPosition(0)
        self.i21.setAlignment(QtCore.Qt.AlignCenter)
        self.i21.setClearButtonEnabled(False)
        self.i21.setObjectName("i21")
        self.i22 = QtWidgets.QLineEdit(self.centralwidget)
        self.i22.setGeometry(QtCore.QRect(170, 130, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i22.setFont(font)
        self.i22.setMaxLength(1)
        self.i22.setFrame(False)
        self.i22.setCursorPosition(0)
        self.i22.setAlignment(QtCore.Qt.AlignCenter)
        self.i22.setClearButtonEnabled(False)
        self.i22.setObjectName("i22")
        self.i33 = QtWidgets.QLineEdit(self.centralwidget)
        self.i33.setGeometry(QtCore.QRect(280, 240, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i33.setFont(font)
        self.i33.setMaxLength(1)
        self.i33.setFrame(False)
        self.i33.setCursorPosition(0)
        self.i33.setAlignment(QtCore.Qt.AlignCenter)
        self.i33.setClearButtonEnabled(False)
        self.i33.setObjectName("i33")
        self.i35 = QtWidgets.QLineEdit(self.centralwidget)
        self.i35.setGeometry(QtCore.QRect(500, 240, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i35.setFont(font)
        self.i35.setMaxLength(1)
        self.i35.setFrame(False)
        self.i35.setCursorPosition(0)
        self.i35.setAlignment(QtCore.Qt.AlignCenter)
        self.i35.setClearButtonEnabled(False)
        self.i35.setObjectName("i35")
        self.i34 = QtWidgets.QLineEdit(self.centralwidget)
        self.i34.setGeometry(QtCore.QRect(390, 240, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i34.setFont(font)
        self.i34.setMaxLength(1)
        self.i34.setFrame(False)
        self.i34.setCursorPosition(0)
        self.i34.setAlignment(QtCore.Qt.AlignCenter)
        self.i34.setClearButtonEnabled(False)
        self.i34.setObjectName("i34")
        self.i31 = QtWidgets.QLineEdit(self.centralwidget)
        self.i31.setGeometry(QtCore.QRect(60, 240, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i31.setFont(font)
        self.i31.setMaxLength(1)
        self.i31.setFrame(False)
        self.i31.setCursorPosition(0)
        self.i31.setAlignment(QtCore.Qt.AlignCenter)
        self.i31.setClearButtonEnabled(False)
        self.i31.setObjectName("i31")
        self.i32 = QtWidgets.QLineEdit(self.centralwidget)
        self.i32.setGeometry(QtCore.QRect(170, 240, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i32.setFont(font)
        self.i32.setMaxLength(1)
        self.i32.setFrame(False)
        self.i32.setCursorPosition(0)
        self.i32.setAlignment(QtCore.Qt.AlignCenter)
        self.i32.setClearButtonEnabled(False)
        self.i32.setObjectName("i32")
        self.i43 = QtWidgets.QLineEdit(self.centralwidget)
        self.i43.setGeometry(QtCore.QRect(280, 350, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i43.setFont(font)
        self.i43.setMaxLength(1)
        self.i43.setFrame(False)
        self.i43.setCursorPosition(0)
        self.i43.setAlignment(QtCore.Qt.AlignCenter)
        self.i43.setClearButtonEnabled(False)
        self.i43.setObjectName("i43")
        self.i45 = QtWidgets.QLineEdit(self.centralwidget)
        self.i45.setGeometry(QtCore.QRect(500, 350, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i45.setFont(font)
        self.i45.setMaxLength(1)
        self.i45.setFrame(False)
        self.i45.setCursorPosition(0)
        self.i45.setAlignment(QtCore.Qt.AlignCenter)
        self.i45.setClearButtonEnabled(False)
        self.i45.setObjectName("i45")
        self.i44 = QtWidgets.QLineEdit(self.centralwidget)
        self.i44.setGeometry(QtCore.QRect(390, 350, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i44.setFont(font)
        self.i44.setMaxLength(1)
        self.i44.setFrame(False)
        self.i44.setCursorPosition(0)
        self.i44.setAlignment(QtCore.Qt.AlignCenter)
        self.i44.setClearButtonEnabled(False)
        self.i44.setObjectName("i44")
        self.i41 = QtWidgets.QLineEdit(self.centralwidget)
        self.i41.setGeometry(QtCore.QRect(60, 350, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i41.setFont(font)
        self.i41.setMaxLength(1)
        self.i41.setFrame(False)
        self.i41.setCursorPosition(0)
        self.i41.setAlignment(QtCore.Qt.AlignCenter)
        self.i41.setClearButtonEnabled(False)
        self.i41.setObjectName("i41")
        self.i42 = QtWidgets.QLineEdit(self.centralwidget)
        self.i42.setGeometry(QtCore.QRect(170, 350, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i42.setFont(font)
        self.i42.setMaxLength(1)
        self.i42.setFrame(False)
        self.i42.setCursorPosition(0)
        self.i42.setAlignment(QtCore.Qt.AlignCenter)
        self.i42.setClearButtonEnabled(False)
        self.i42.setObjectName("i42")
        self.i53 = QtWidgets.QLineEdit(self.centralwidget)
        self.i53.setGeometry(QtCore.QRect(280, 460, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i53.setFont(font)
        self.i53.setMaxLength(1)
        self.i53.setFrame(False)
        self.i53.setCursorPosition(0)
        self.i53.setAlignment(QtCore.Qt.AlignCenter)
        self.i53.setClearButtonEnabled(False)
        self.i53.setObjectName("i53")
        self.i55 = QtWidgets.QLineEdit(self.centralwidget)
        self.i55.setGeometry(QtCore.QRect(500, 460, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i55.setFont(font)
        self.i55.setMaxLength(1)
        self.i55.setFrame(False)
        self.i55.setCursorPosition(0)
        self.i55.setAlignment(QtCore.Qt.AlignCenter)
        self.i55.setClearButtonEnabled(False)
        self.i55.setObjectName("i55")
        self.i54 = QtWidgets.QLineEdit(self.centralwidget)
        self.i54.setGeometry(QtCore.QRect(390, 460, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i54.setFont(font)
        self.i54.setMaxLength(1)
        self.i54.setFrame(False)
        self.i54.setCursorPosition(0)
        self.i54.setAlignment(QtCore.Qt.AlignCenter)
        self.i54.setClearButtonEnabled(False)
        self.i54.setObjectName("i54")
        self.i51 = QtWidgets.QLineEdit(self.centralwidget)
        self.i51.setGeometry(QtCore.QRect(60, 460, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i51.setFont(font)
        self.i51.setMaxLength(1)
        self.i51.setFrame(False)
        self.i51.setCursorPosition(0)
        self.i51.setAlignment(QtCore.Qt.AlignCenter)
        self.i51.setClearButtonEnabled(False)
        self.i51.setObjectName("i51")
        self.i52 = QtWidgets.QLineEdit(self.centralwidget)
        self.i52.setGeometry(QtCore.QRect(170, 460, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i52.setFont(font)
        self.i52.setMaxLength(1)
        self.i52.setFrame(False)
        self.i52.setCursorPosition(0)
        self.i52.setAlignment(QtCore.Qt.AlignCenter)
        self.i52.setClearButtonEnabled(False)
        self.i52.setObjectName("i52")
        self.i63 = QtWidgets.QLineEdit(self.centralwidget)
        self.i63.setGeometry(QtCore.QRect(280, 570, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i63.setFont(font)
        self.i63.setMaxLength(1)
        self.i63.setFrame(False)
        self.i63.setCursorPosition(0)
        self.i63.setAlignment(QtCore.Qt.AlignCenter)
        self.i63.setClearButtonEnabled(False)
        self.i63.setObjectName("i63")
        self.i65 = QtWidgets.QLineEdit(self.centralwidget)
        self.i65.setGeometry(QtCore.QRect(500, 570, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i65.setFont(font)
        self.i65.setMaxLength(1)
        self.i65.setFrame(False)
        self.i65.setCursorPosition(0)
        self.i65.setAlignment(QtCore.Qt.AlignCenter)
        self.i65.setClearButtonEnabled(False)
        self.i65.setObjectName("i65")
        self.i64 = QtWidgets.QLineEdit(self.centralwidget)
        self.i64.setGeometry(QtCore.QRect(390, 570, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i64.setFont(font)
        self.i64.setMaxLength(1)
        self.i64.setFrame(False)
        self.i64.setCursorPosition(0)
        self.i64.setAlignment(QtCore.Qt.AlignCenter)
        self.i64.setClearButtonEnabled(False)
        self.i64.setObjectName("i64")
        self.i61 = QtWidgets.QLineEdit(self.centralwidget)
        self.i61.setGeometry(QtCore.QRect(60, 570, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i61.setFont(font)
        self.i61.setMaxLength(1)
        self.i61.setFrame(False)
        self.i61.setCursorPosition(0)
        self.i61.setAlignment(QtCore.Qt.AlignCenter)
        self.i61.setClearButtonEnabled(False)
        self.i61.setObjectName("i61")
        self.i62 = QtWidgets.QLineEdit(self.centralwidget)
        self.i62.setGeometry(QtCore.QRect(170, 570, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.i62.setFont(font)
        self.i62.setMaxLength(1)
        self.i62.setFrame(False)
        self.i62.setCursorPosition(0)
        self.i62.setAlignment(QtCore.Qt.AlignCenter)
        self.i62.setClearButtonEnabled(False)
        self.i62.setObjectName("i62")
        self.confirm = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.gameRound())
        self.confirm.setGeometry(QtCore.QRect(280, 690, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.confirm.setFont(font)
        self.confirm.setObjectName("confirm")
        self.confirm.setStyleSheet("background-color: #808388 ;border: 1px solid #white")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 666, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        for i in range(11, 16):
            exec(f"self.i{i}.setStyleSheet(\"background-color: #3A3B3C ;border: 1px solid #808080;\") ")
        for i in range(21, 26):
            exec(f"self.i{i}.setStyleSheet(\"background-color: #3A3B3C ;border: 1px solid #808080;\") ")
            exec(f"self.i{i}.setReadOnly(True) ")
        for i in range(31, 36):
            exec(f"self.i{i}.setStyleSheet(\"background-color: #3A3B3C ;border: 1px solid #808080;\") ")
            exec(f"self.i{i}.setReadOnly(True) ")
        for i in range(41, 46):
            exec(f"self.i{i}.setStyleSheet(\"background-color: #3A3B3C ;border: 1px solid #808080;\") ")
            exec(f"self.i{i}.setReadOnly(True) ")
        for i in range(51, 56):
            exec(f"self.i{i}.setStyleSheet(\"background-color: #3A3B3C ;border: 1px solid #808080;\") ")
            exec(f"self.i{i}.setReadOnly(True) ")
        for i in range(61, 66):
            exec(f"self.i{i}.setStyleSheet(\"background-color: #3A3B3C ;border: 1px solid #808080;\") ")
            exec(f"self.i{i}.setReadOnly(True) ")

        self.board = [
            [self.i11, self.i12, self.i13, self.i14, self.i15],
            [self.i21, self.i22, self.i23, self.i24, self.i25],
            [self.i31, self.i32, self.i33, self.i34, self.i35],
            [self.i41, self.i42, self.i43, self.i44, self.i45],
            [self.i51, self.i52, self.i53, self.i54, self.i55],
            [self.i61, self.i62, self.i63, self.i64, self.i65],
        ]

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.word = randomWord(array)
        print(self.word)

    def gameRound(self):
        print(self.word)
        x = self.round
        a = self.board[x-1][0].text()
        b = self.board[x-1][1].text()
        c = self.board[x-1][2].text()
        d = self.board[x-1][3].text()
        e = self.board[x-1][4].text()
        guess = concatenate(a, b, c, d, e)

        if not check(array, guess, 0, len(array)):
            for i in range(x*10+1, x*10+6):
                exec(f"self.i{i}.setStyleSheet(\"background-color: #B31B1B ;border: 1px solid #B31B1B;\") ")
        else:
            res = round(guess,self.word)
            if checkWin(res):
                for i in range(x * 10 + 1, x * 10 + 6):
                    exec(f"self.i{i}.setStyleSheet(\"background-color: #40ba0f ;border: 1px solid #40ba0f;\") ")
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Information)
                    msg.setText("You Won!!")
                    msg.setWindowTitle("Result")
                    msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
                    retval = msg.exec_()

            else:
                for i in range(5):
                    if res[i] == 0:
                        self.board[x-1][i].setStyleSheet("background-color: #3A3B3C ;border: 1px solid #808080;")
                    elif res[i] == 2:
                        self.board[x-1][i].setStyleSheet("background-color: #40ba0f ;border: 1px solid #40ba0f;")
                    else:
                        self.board[x-1][i].setStyleSheet("background-color: #f2db00 ;border: 1px solid #f2db00;")
            self.round = self.round + 1
            if self.round == 7 and not checkWin(res):
                print("HI")
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("You Lost. The word was " + word)
                msg.setWindowTitle("Result")
                msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
                retval = msg.exec_()

            for i in range(x*10+1, x*10+6):
                exec(f"self.i{i}.setReadOnly(True) ")
            for i in range((x+1)*10+1, (x+1)*10+6):
                exec(f"self.i{i}.setReadOnly(False) ")


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WORDLE"))
        MainWindow.setWindowIcon(QtGui.QIcon("icon.jpg"))
        self.confirm.setText(_translate("MainWindow", "Confirm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setCursorFlashTime(0)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
